api:
  external:
    zipcode:
      url: ${SERVICE_ZIPCODE_URL:https://viacep.com.br/ws/}
  security:
    admin:
      password: ${ADM_PASSWORD_DEFAULT}
      cpf: ${ADM_CPF_DEFAULT}
    algorithm: ${ALG_SECRET}
spring:
  datasource:
    url: jdbc:mysql://localhost/address_manager
    username: ${BD_USER}
    password: ${BD_SECRET}